Logger.emit failing, moved to process.stderr
Was receiving a `TypeError: Logger.emit is not a function`, so I moved it to just using a stderr function to inform users on startup of a failure to log to file.